Web/Models/AnnounceResult.cs
using System.Collections.Generic;
using Umbraco.Web.PublishedContentModels;

namespace Web.Models
{
    public class AnnounceResult : Pager
    {
        public List<AnnounceItem> Items { get; set; }
    }
}

Web/Models/GalleryResult.cs
using System.Collections.Generic;
using Umbraco.Web.PublishedContentModels;

namespace Web.Models
{
    public class GalleryResult : Pager
    {
        public List<GalleryItem> Items { get; set; }

        public string Title { get; set; }
    }
}

Web/Models/NewsResult.cs
using System.Collections.Generic;
using Umbraco.Core.Models;
using Umbraco.Web.PublishedContentModels;

namespace Web.Models
{
    public class NewsResult : Pager
    {
        public List<NewsItem> Items { get; set; }
    }
}

Web/Models/Pager.cs
namespace Web.Models
{
    public class Pager //: RenderModel
    {
        //public NewsPager()
        //    : base(UmbracoContext.Current.PublishedContentRequest.PublishedContent)
        //{
        //}

        public int Page { get; set; }

        public int TotalPages { get; set; }
    }
}

Web/Controllers/AnnounceController.cs
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using Web.Helpers;

namespace Web.Controllers
{
    public class AnnounceController : SurfaceController
    {
        #region Actions

        //[ChildActionOnly]
        [HttpPost]
        public ActionResult Index(int page, int itemsPerPage)
        {
            //System.Threading.Thread.Sleep(1000);

            var model = ContentManager.GetAnnounceItems(page, itemsPerPage);
            return PartialView("~/Views/Partials/Announce/AnnouncesList.cshtml", model);
        }

        #endregion
    }
}

Web/Controllers/ContactFormController.cs
using System;
using System.Text;
using System.Web;
using System.Web.Mvc;
using HtmlAgilityPack;
using Logic.Models;
using Logic.Resources;
using Umbraco.Core.Logging;
using Umbraco.Web.Mvc;
using Web.Helpers;

namespace Web.Controllers
{
    public class ContactFormController : SurfaceController
    {
        #region Actions

        [HttpPost]
        public JsonResult Send(ContactForm model)
        {
            var success = true;
            try
            {
                if (!ModelState.IsValid)
                {
                    success = false;
                }

                var body = GetMailBody(model);

                Utils.SendEmail(model.EmailFrom,
                    model.EmailTo,
                    Localization.ContactFormEmailSubject,
                    body);
            }
            catch (Exception e)
            {
                LogHelper.Error(GetType(), e.ToString(), e);
                success = false;
            }
            return Json(new { success });
        }

        [ChildActionOnly]
        public ActionResult Index(string emailFrom, string emailTo)
        {
            return PartialView("~/Views/Partials/Common/ContactForm.cshtml", new ContactForm { EmailFrom = emailFrom, EmailTo = emailTo });
        }

        #endregion

        #region Helpers

        private string GetMailBody(ContactForm model)
        {
            var doc = new HtmlDocument();
            doc.Load(Server.MapPath("~/Email/ContactForm.html"));
            var builder = new StringBuilder(doc.DocumentNode.SelectSingleNode("//body").WriteTo());

            ReplacePlaceholder(builder, "NameSurnameTitle", Localization.ContactFormNameSurname);
            ReplacePlaceholder(builder, "NameSurname", model.NameSurname);

            ReplacePlaceholder(builder, "ClientEmailTitle", Localization.ContactFormClientEmail);
            ReplacePlaceholder(builder, "ClientEmail", model.ClientEmail);

            ReplacePlaceholder(builder, "DescriptionTitle", Localization.ContactFormDescription);
            ReplacePlaceholder(builder, "Description", model.Description);

            return builder.ToString();
        }

        private void ReplacePlaceholder(StringBuilder builder, string key, string value)
        {
            key = $"[{key}]";
            value = HttpUtility.HtmlEncode(value);
            builder.Replace(key, value);
        }

        #endregion
    }
}

Web/Controllers/GalleryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Umbraco.Web;
using Umbraco.Web.Mvc;
using Umbraco.Web.PublishedContentModels;
using Web.Helpers;
using GalleryResult = Web.Models.GalleryResult;

namespace Web.Controllers
{
    public class GalleryController : SurfaceController
    {
        [HttpPost]
        public ActionResult Index(int year, int page, int itemsPerPage)
        {
            //System.Threading.Thread.Sleep(1000);
            var model = ContentManager.GetGalleryItems(year, page, itemsPerPage);
            return PartialView("~/Views/Partials/Gallery/GalleryList.cshtml", model);
        }
    }
}

Web/Controllers/NewsController.cs
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using Web.Helpers;

namespace Web.Controllers
{
    public class NewsController : SurfaceController
    {
        #region Actions

        //[ChildActionOnly]
        [HttpPost]
        public ActionResult Index(int year, int page, int itemsPerPage)
        {
            //System.Threading.Thread.Sleep(1000);

            var model = ContentManager.GetNewsItems(year, page, itemsPerPage);
            return PartialView("~/Views/Partials/News/NewsList.cshtml", model);
        }

        #endregion
    }
}

Web/Controllers/SearchController.cs
using System.Linq;
using System.Web.Mvc;
using Examine;
using UmbracoExamine;
using Examine.LuceneEngine.SearchCriteria;
using Examine.SearchCriteria;
using Lucene.Net.Search;
using Umbraco.Web.Mvc;

namespace Web.Controllers
{
    public class SearchController : SurfaceController
    {
        [HttpPost]
        public ActionResult Index(string text)
        {
            var searcher = ExamineManager.Instance.SearchProviderCollection["ExternalSearcher"];
            var searchCriteria = searcher.CreateSearchCriteria(BooleanOperation.Or);
            var searchFields = new[] {"nodeName", "metaTitle"};
            var query = searchCriteria.GroupedOr(searchFields, text.Fuzzy(0.8f)).Compile();
            var searchResults = searcher.Search(query).OrderByDescending(x => x.Score);
            return null;
        }
    }
}

Web/Controllers/TabbedPageController.cs
using System;
using System.Globalization;
using System.IO;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using Umbraco.Forms.Web.Helpers;
using Umbraco.Web.Mvc;
using Umbraco.Web.PublishedContentModels;
using Umbraco.Web.Routing;
using Umbraco.Web.WebApi;
using Web.Helpers;

namespace Web.Controllers
{
    public class TabbedPageController : SurfaceController
    {
        #region Actions

        //[ChildActionOnly]
        //[HttpPost]
        //public ActionResult GetTabContent(int pageId)
        //{
        //    //Umbraco
        //    System.Threading.Thread.CurrentThread.CurrentUICulture = new CultureInfo("uk-UA", false);
        //    var page = (TextPage)ContentManager.GetPage(pageId);
        //    UmbracoContext.PublishedContentRequest =
        //        new PublishedContentRequest(Request.Url, UmbracoContext.RoutingContext);
        //    return PartialView("~/Views/Partials/TabbedPage/TabContent.cshtml", page);
        //}

        #endregion
    }
}

Web/Views/AnnounceItem.cshtml
@inherits UmbracoTemplatePage<AnnounceItem>
@{
    Layout = "ContentBase.cshtml";
    var item = Model.Content;
    var parent = item.Parent;
    //var overviewTitle = item.Ancestor<AnnounceOverview>().Title;
    var title = item.GetTitle();
    var dict = new ViewDataDictionary { { "showTime", true } };
    var btnBackId = "btn-back";
    var fallbackUrl = parent.Url + "#/";
}

@section RightSidebar
{
    @*<div class="standart-right-sidebar">
            @{Html.RenderPartial("~/Views/Partials/Common/Calendar.cshtml");}
    </div>*@
}

@section Body{
    <article class="announce-item-container">
        <header class="title">
            <a id="@btnBackId" class="btn-back" href="#"></a>
            <div class="text">
                <h3>@title</h3>
                @{ Html.RenderPartial("/Views/Partials/Common/ArticleInfo.cshtml", item, dict);}
            </div>
        </header>
        <div class="grid-content">
            @Html.GetGridHtml(item, AnnounceItem.GetModelPropertyType(i => i.Content).PropertyTypeAlias, "Custom")
        </div>
        @{Html.RenderPartial("~/Views/Partials/Common/Comments.cshtml");}
    </article>

    <script type="text/javascript">
        $(function () {
            InitBackButton('@btnBackId', '@fallbackUrl');
        });
    </script>
}

Web/Views/AnnounceOverview.cshtml
@inherits UmbracoTemplatePage<AnnouncesOverview>
@{
    Layout = "ContentBase.cshtml";
    var containerId = "announces-list";
    var overlayId = "loading-overlay";
}

@*@section RightSidebar
    {
        <div class="standart-right-sidebar">
            @{Html.RenderPartial("~/Views/Partials/Common/Calendar.cshtml");}
        </div>
    }*@

@section Body{
    <section class="announce-overview-container">
        <header class="header">
            <div class="row">
                <div class="col-sm-24">
                    <h2>@Model.Content.GetTitle()</h2>
                </div>
            </div>
        </header>
        <div id="@containerId" class="list"></div>
        <div id="@overlayId" class="loading-overlay"></div>
    </section>

    <script type="text/javascript">
        $(function () {
            announcesRouting.init({
                containerId: '@containerId',
                overlayId: '@overlayId',
                itemsPerPage: @Consts.AnnouncesConfig.ItemsPerPageOnOverviewPage});
        });
    </script>
}

Web/Views/BlogOverview.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}

<div role="content">

	<section class="light blogarchive equalizer">
		<div class="container">

			<div class="row">
				@foreach(var post in CurrentPage.Children) 
				{
					<div class="col-sm-6">
						<div class="content equal">
							<a href="@post.Url">
								<div class="date">@post.CreateDate.ToLongDateString()</div>
								<h2>@post.Name</h2>		
								<p>@Umbraco.Truncate(post.Introduction, 240, true)</p>
							</a>
						</div>
					</div>
				}
			</div>
		</div>
	</section>

</div>

Web/Views/BlogPost.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}

@CurrentPage.GetGridHtml("content", "fanoe")

Web/Views/ContentBase.cshtml
@inherits UmbracoTemplatePage
@{
    Layout = "LayoutBase.cshtml";
    var leftSidebarDefined = IsSectionDefined("LeftSidebar");
    var rightSidebarDefined = IsSectionDefined("RightSidebar");

    var leftSidebarWidth = 6;
    var rightSidebarWidth = 6;
    var allWidth = 24;
    var contentWidth = allWidth;
    string cssClass = "no-sidebars-defined";
    if (leftSidebarDefined && rightSidebarDefined)
    {
        contentWidth = allWidth - leftSidebarWidth - rightSidebarWidth;
        cssClass = "left-sidebar-defined right-sidebar-defined";
    }
    else if (leftSidebarDefined)
    {
        contentWidth = allWidth - leftSidebarWidth;
        cssClass = "left-sidebar-defined";
    }
    else if (rightSidebarDefined)
    {
        contentWidth = allWidth - rightSidebarWidth;
        cssClass = "right-sidebar-defined";
    }
}
@section Scripts{
    @if (IsSectionDefined("Scripts"))
    {
        @RenderSection("Scripts")
    }
}

<section class="main-wrapper">
    <div class="container">
        <div class="row">
            @if (leftSidebarDefined)
            {
                <section class="col-sm-@leftSidebarWidth">
                    @RenderSection("LeftSidebar")
                </section>
            }
            <section class="col-sm-@contentWidth @cssClass">
                @RenderSection("Body")
            </section>
            @if (rightSidebarDefined)
            {
                <section class="col-sm-@rightSidebarWidth">
                    @RenderSection("RightSidebar")
                </section>
            }
        </div>
    </div>
</section>

Web/Views/GalleryItem.cshtml
@inherits UmbracoTemplatePage<GalleryItem>
@{
    Layout = "ContentBase.cshtml";

    var item = Model.Content;
    var parent = item.Parent;
    var title = item.GetTitle();
    var imageIds = item.Images.Split(new[] { "," }, StringSplitOptions.RemoveEmptyEntries).Select(int.Parse);
    var images = Umbraco.TypedMedia(imageIds);
    var id = "gallery-item";
    var btnBackId = "btn-back";
    var fallbackUrl = parent.Url + "#/";
}
@section Body
{
    <article class="gallery-item-container" id="@id">
        <header class="title">
            <a id="@btnBackId" class="btn-back" href="#"></a>
            <div class="text">
                <h3>
                    @title
                </h3>
                <span>@item.Subtitle</span>
            </div>
        </header>
        <section class="images">
            <div class="row">
                @foreach (var image in images)
                {
                    var url = image.Url;
                    <div class="col-sm-6">
                        <a href="@url" class="image">
                            <img class="img-responsive" src="@Html.GetThumbnailUrl(url, 300, 300)" alt="" />
                        </a>
                    </div>
                }
            </div>
        </section>
    </article>

    <script type="text/javascript">
        $(function () {
            InitGalleryItem('@id');
            InitBackButton('@btnBackId', '@fallbackUrl');
        });
    </script>
}

Web/Views/GalleryOverview.cshtml
@inherits UmbracoTemplatePage<GalleryOverview>
@{
    Layout = "ContentBase.cshtml";
    var containerId = "gallery-list";
    var overlayId = "loading-overlay";
    var galleryYears = ContentManager.GetGalleryYears();
    var dict = new ViewDataDictionary
    {
        { "DataAttr", "data-gallery-link" },
        { "RoutingObj", "galleryRouting" }
    };
}

@section Body
{
    <section class="gallery-overview-container">
        <header class="header">
            <div class="row">
                <div class="col-sm-18">
                    <h2>@Model.Content.GetTitle()</h2>
                </div>
                <div class="col-sm-6">
                    @{Html.RenderPartial("~/Views/Partials/Common/YearsList.cshtml", galleryYears, dict);}
                </div>
            </div>
        </header>
        <div class="list" id="@containerId"></div>
        <div id="@overlayId" class="loading-overlay"></div>
    </section>

    <script type="text/javascript">
        $(function () {
            galleryRouting.init({
                containerId: '@containerId',
                overlayId: '@overlayId',
                yearAllInt: @Consts.GalleryConfig.YearAllInt,
                itemsPerPage: @Consts.GalleryConfig.ItemsPerPageOnOverviewPage});
        });
    </script>
}

Web/Views/Home.cshtml
@inherits UmbracoTemplatePage<Home>
@{
    Layout = "LayoutBase.cshtml";
}
@{Html.RenderPartial("~/Views/Partials/Home/BannerCarousel.cshtml");}
@{Html.RenderPartial("~/Views/Partials/Home/Announces.cshtml");}
@{Html.RenderPartial("~/Views/Partials/Home/Info.cshtml");}
@{Html.RenderPartial("~/Views/Partials/Home/News.cshtml");}
@{Html.RenderPartial("~/Views/Partials/Home/Gallery.cshtml");}

Web/Views/LayoutBase.cshtml
@inherits UmbracoTemplatePage
@{
    Layout = null;
    var site = Model.Content.AncestorOrSelf<Site>();
    var page = Model.Content;
    var siteName = site.SiteName;
    var siteDescription = site.SiteDescription;
    var pageTitle = page.GetTitle();
}
<!DOCTYPE html>
<html>
<head>
    <title>@pageTitle - @siteName</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    @*<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">*@
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="@siteDescription" />
    <meta name="keywords" content="" />
    <link rel="icon" type="image/x-icon" href="/favicon.ico" />
    @Styles.Render("~/css/site.css")
    @Scripts.Render("~/js/site.js")
    @if (IsSectionDefined("Scripts"))
    {
        @RenderSection("Scripts")
    }
    <script id="dsq-count-scr" src="//spadschyna.disqus.com/count.js" async></script>
</head>
<body>
    <!-- /Header -->
    @{ Html.RenderPartial("~/Views/Partials/Common/ScrollToTop.cshtml"); }
    @{ Html.RenderPartial("~/Views/Partials/Common/LoadingSpinner.cshtml"); }
    @{ Html.RenderPartial("~/Views/Partials/Common/Header.cshtml"); }
    @RenderBody()
    @{ Html.RenderPartial("~/Views/Partials/Common/Footer.cshtml"); }
</body>
</html>

Web/Views/LayoutCustom.cshtml
@{
    Layout = null;
}
@RenderBody()

Web/Views/MacroPartials/BoardMembers.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@{
    var container = Model.Content
        .AncestorOrSelf(1)
        .FirstChild<BoardContainer>();
    var items = container
        .Children<BoardMember>()
        .ToList();

}

@if (Request.RawUrl.Contains("GetMacroResultAsHtmlForEditor"))
{
    <span>@container.GetTitle()</span>
}
else
{
    <article class="board-members-container">
        @*<header class="title">
                <h2>@container.GetTitle()</h2>
        </header>*@
        <div class="row">
            @for (var i = 0; i < items.Count; i++)
            {
                var item = items[i];
                var image = item.Image;
                <div class="col-sm-8">
                    <article class="board-member center-block">
                        @if (image != null)
                        {
                            var imageUrl = image.Src + image.GetCropUrl(image.Crops.First().Alias);
                            <img class="img-responsive img-circle" src="@imageUrl" alt="" />
                        }
                        <header class="title">
                            <h4>@item.GetTitle()</h4>
                        </header>
                        <div class="pseudo">@item.Pseudo</div>
                        <div class="management-area">@item.ManagementArea</div>
                    </article>
                </div>
                if ((i + 1) % 3 == 0)
                {
                    <div class="clearfix hidden-xs"></div>
                }
            }
        </div>
    </article>
}

Web/Views/MacroPartials/ContactForm.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@{
    var emailFrom = (string)Model.MacroParameters["EmailFrom"];
    var emailTo = (string)Model.MacroParameters["EmailTo"];
}

@Html.Action("Index", "ContactForm", new { emailFrom, emailTo })

Web/Views/MacroPartials/GoogleMap.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@{
    var latitude = Convert.ToString(Model.MacroParameters["Latitude"]);
    var longitude = Convert.ToString(Model.MacroParameters["Longitude"]);
    var title = (string)Model.MacroParameters["Title"];
    var height = Convert.ToInt32(Model.MacroParameters["MapHeight"]);
    var zoom = Convert.ToInt32(Model.MacroParameters["MapZoom"]);

    var id = Utils.GenerateId("googleMap");
}

<article id="@id" class="google-map-container" style="height:@(height)px"></article>

<script type="text/javascript">
    function initMap() {
        var settings = {
            longitude: @longitude,
            latitude: @latitude,
            title: "@title",
            height: @height,
            zoom: @zoom,
            id: "@id"
        };
        InitGoogleMap(settings);
    }
</script>

<script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCl9lmZDJob7gDTZ_QGKD9LIuzr8L759o0&callback=initMap&language=uk">
</script>

Web/Views/MacroPartials/ImagesCarousel.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@{
    var carouselImagesStr = (string)Model.MacroParameters["Images"];
    var imageIds = carouselImagesStr.Split(new[] { "," }, StringSplitOptions.RemoveEmptyEntries).Select(int.Parse);
    var carouselImages = Umbraco.Media(imageIds);
}

@if (Request.RawUrl.Contains("GetMacroResultAsHtmlForEditor"))
{
    /*Render differently in backoffice*/
    <span>Images carousel with @carouselImages.Count() images</span>
}
else
{
    var dict = new ViewDataDictionary { { "carouselImages", carouselImages } };
    Html.RenderPartial("/Views/Partials/Common/ImagesCarousel.cshtml", dict);
}

Web/Views/MacroPartials/InsertUmbracoForm.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage

	
	
@if (Model.MacroParameters["FormGuid"] != null)
{
    var s = Model.MacroParameters["FormGuid"].ToString();
    var g = new Guid(s);
    
	Html.RenderAction("Render", "UmbracoForms", new {formId = g});
}

Web/Views/MacroPartials/RenderUmbracoFormScripts.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@using Umbraco.Forms.Web.Controllers

@if (TempData["UmbracoForms"] != null)
{
    foreach (var form in (List<Guid>)TempData["UmbracoForms"])
    {
        Html.RenderAction("Render", "UmbracoForms", new { formId = form, mode = "script"});
    }
}
    

Web/Views/NewsItem.cshtml
@inherits UmbracoTemplatePage<NewsItem>
@{
    Layout = "ContentBase.cshtml";

    var item = Model.Content;
    var parent = item.Parent;
    //var overviewTitle = item.Ancestor<NewsOverview>().Title;
    var title = item.GetTitle();
    var btnBackId = "btn-back";
    var fallbackUrl = parent.Url + "#/";
}

@section RightSidebar
{
    <div class="standart-right-sidebar">
        @*@{Html.RenderPartial("~/Views/Partials/Common/Calendar.cshtml");}*@
        @{Html.RenderPartial("~/Views/Partials/Common/LatestNews.cshtml");}
    </div>
}

@section Body
{
    <article class="news-item-container">
        <header class="title">
            <a id="@btnBackId" class="btn-back" href="#"></a>
            <div class="text">
                <h3>@title</h3>
                @{ Html.RenderPartial("/Views/Partials/Common/ArticleInfo.cshtml", item);}
                @{ Html.RenderPartial("/Views/Partials/Common/ArticleTags.cshtml", item);}
            </div>
        </header>
        <div class="grid-content">
            @Html.GetGridHtml(item, NewsItem.GetModelPropertyType(i => i.Content).PropertyTypeAlias, "Custom")
        </div>
        @{Html.RenderPartial("~/Views/Partials/Common/Comments.cshtml");}
    </article>

    <script type="text/javascript">
        $(function () {
            InitBackButton('@btnBackId', '@fallbackUrl');
        });
    </script>
}

Web/Views/NewsOverview.cshtml
@inherits UmbracoTemplatePage<NewsOverview>
@{
    Layout = "ContentBase.cshtml";
    var item = Model.Content;
    var containerId = "news-list";
    var overlayId = "loading-overlay";
    var newsYears = ContentManager.GetNewsYears();
    var dict = new ViewDataDictionary
    {
        { "DataAttr", "data-news-link" },
        { "RoutingObj", "newsRouting" }
    };
}

@section Body
{
    <section class="news-overview-container">
        <header class="header">
            <div class="row">
                <div class="col-sm-18">
                    <h2>@Model.Content.GetTitle()</h2>
                </div>
                <div class="col-sm-6">
                    @{Html.RenderPartial("~/Views/Partials/Common/YearsList.cshtml", newsYears, dict);}
                </div>
            </div>
        </header>
        <div id="@containerId" class="list"></div>
        <div id="@overlayId" class="loading-overlay"></div>
    </section>


    <script type="text/javascript">
        $(function () {
            newsRouting.init({
                containerId: '@containerId',
                overlayId: '@overlayId',
                yearAllInt: @Consts.NewsConfig.YearAllInt,
                itemsPerPage: @Consts.NewsConfig.ItemsPerPageOnOverviewPage});
        });
    </script>
}

Web/Views/Partials/Announce/AnnouncesList.cshtml
@inherits UmbracoViewPage<AnnounceResult>
@{
    var items = Model.Items;
}

@foreach (var item in items)
{
    var title = item.GetTitle();
    var image = item.Image;
    var imageUrl = image != null ? image.Src + image.GetCropUrl(image.Crops.First().Alias) :
        Utils.GetImageNotFoundUrl(Consts.AnnouncesConfig.ThumbImgWidth, Consts.AnnouncesConfig.ThumbImgHeight);
    var subHeader = item.Subtitle;
    var content = new HtmlString(string.Empty); // can't parse content as we are now using Grid Layout
    var dict2 = new ViewDataDictionary { { "showTime", true } };

    <article class="announce-item">
        <div class="row">
            <div class="col-md-20 col-lg-18">
                <div class="row">
                    <div class="col-sm-8">
                        <a href="@item.Url" class="image">
                            <img class="img-responsive" src="@imageUrl" alt=""/>
                        </a>
                    </div>
                    <div class="col-sm-16">
                        <header class="title">
                            <h4>
                                <a href="@item.Url">@title</a>
                            </h4>
                        </header>
                        @{
                            if (!string.IsNullOrEmpty(subHeader))
                            {
                                <div class="byline">
                                    @Html.GetInnerText(string.IsNullOrWhiteSpace(subHeader) ?
                                        content : new HtmlString(subHeader), 200)
                                    <a href="@item.Url">@Localization.ItemReadMore</a>
                                </div>
                            }
                        }
                        @{ Html.RenderPartial("/Views/Partials/Common/ArticleInfo.cshtml", item, dict2);}
                        <hr class="break-line visible-xs"/>
                    </div></div>
            </div>
        </div>
    </article>
                        }

@{
    var dict = new ViewDataDictionary
    {
        { "DataAttr", "data-announce-link" },
        { "RoutingObj", "announcesRouting" }
    };
    Html.RenderPartial("~/Views/Partials/Common/ArticlesPager.cshtml", Model, dict);
}

Web/Views/Partials/Forms/Fieldtypes/FieldType.CheckBox.cshtml
@model Umbraco.Forms.Mvc.Models.FieldViewModel    
<input type="checkbox" name="@Model.Name" id="@Model.Id" 
    @if(Model.Mandatory){<text>  data-val="true" data-val-requiredcb="@Model.RequiredErrorMessage"</text>}
    @if (Model.ContainsValue(true) || Model.ContainsValue("true") || Model.ContainsValue("on"))
    {<text>checked="checked"</text>}       
                                                                                                         
    />

Web/Views/Partials/Forms/Fieldtypes/FieldType.HiddenField.cshtml
@model Umbraco.Forms.Mvc.Models.FieldViewModel
<input type="hidden" name="@Model.Name" id="@Model.Id" class="hidden" value="@Model.Value"/>

Web/Views/Partials/Grid/Editors/ColouredHeader.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<dynamic>
<header class="header-coloured with-margin @Model.headerValue.colour">
    <h4>@Model.headerValue.text</h4>
</header>